version: '3'

services:
  postgres:
    image: postgres
    ports:
      - "5435:5432"
    entrypoint:
      - POSTGRES_USER=iksline
      - POSTGRES_PASSWORD=iksline
      - POSTGRES_DB=iksline
    container_name: 'java-postgres'

  app:
    build: ./
    ports:
      - "8080:8080"
    container_name: 'java-app'
